### ISSUE TITLE
Change Docker with maven jetty plugin

### ISSUE THREAD

**Issue by leosoto** [TransbankDevelopers/transbank-sdk-java-onepay-example#13]
Java is supposed to work the same everywhere, so we shouldn't need a Docker image for this project (unlike the case for PHP where there are a lot of moving parts). We can probably replace the tomcat server with the maven jetty plugin.

**Comment by goncafa** [comment]
I think it could be even easier to run with jetty. I have made with docker because i have never set up it with jetty. I think the only you should care is to maintain a way to setup an environment with the local IP in order to could test in mobile.

**Comment by leosoto** [comment]
Sounds good. I’ll give it a try at some point in the future :)

**Comment by leosoto** [comment]
This is addressed by #15
